### PR TITLE
Added Resize function

### PR DESCRIPTION
**Pull request by kairavkkp**
Please comment if any changes required. 😄

### CODE REVIEW

**Comment by kairavkkp** [comment]
Solves #1

**Comment by PavKmiec** [comment]
Well done, images are resized correctly and the keywords are saved back to original files too.

Only problem I found is the removal of the resized images throws an error on the line with `shutil.rmtree(new_key)`:

```
Traceback (most recent call last):
  File "combine.py", line 61, in <module>
    shutil.rmtree(new_key)
  File "/usr/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.8/shutil.py", line 628, in _rmtree_safe_fd
    onerror(os.scandir, path, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 624, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
NotADirectoryError: [Errno 20] Not a directory: '/home/px/Desktop/repos/pull/Image-Keywording/images/DigitalGlobe_WorldView2_50cm_8bit_Pansharpened_RGB_DRA_Rome_Italy_2009DEC10_8bits_sub_r_1_resized.jpg'
```

**Comment by kairavkkp** [comment]
Let me update it once. I think I might have a solution. 😄

**Comment by kairavkkp** [comment]
`shutil.rmtree()` requires a directory and the element passed into it was the path to an image, hence the error. Replaced `shutil.rmtree()` with `os.remove()` in order to remove an individual file.

**Comment by PavKmiec** [comment]
well done! all works as intended now.

**Comment by kairavkkp** [comment]
Happy to help! 😄

**Pull request merged**
